version: '3'

services:
  mongodb:
    image: mongo:5
    restart: unless-stopped
    container_name: ${MONGO_HOST}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "27018:27017"
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: ['--auth']

  app:
    restart: unless-stopped
    depends_on:
      - mongodb
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    image: laroaccess-app
    container_name: laroaccess_app
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/app/
      - /app/node_modules
    environment:
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      MONGO_HOST: ${MONGO_HOST}
      ROOT_USERNAME: ${ROOT_USERNAME}
      ROOT_PASSWORD: ${ROOT_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_REMOTE_HOST: ${MONGO_REMOTE_HOST}