name: Docker Hub CI
on:
  push:
    branches: ['master']
env:
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Git Semantic Version
        id: GSV
        uses: PaulHatch/semantic-version@v4.0.3
        with:
          major_pattern: 'major:'
          minor_pattern: 'feat:'

      - name: Docker Login
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build Docker image
        env:
          APP_VERSION: ${{ steps.GSV.outputs.version }}
        run: |
          docker build --file Dockerfile --tag $DOCKER_USER/laroaccess:$APP_VERSION .
          docker build --file Dockerfile --tag $DOCKER_USER/laroaccess:latest .

      - name: Push Docker image
        env:
          APP_VERSION: ${{ steps.GSV.outputs.version }}
        run: |
          docker push $DOCKER_USER/laroaccess:$APP_VERSION
          docker push $DOCKER_USER/laroaccess:latest
